# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWidget.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWidget(object):
    def setupUi(self, MainWidget):
        MainWidget.setObjectName("MainWidget")
        MainWidget.resize(599, 334)
        self.tabWidget = QtWidgets.QTabWidget(MainWidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 581, 321))
        self.tabWidget.setObjectName("tabWidget")
        self.LPR = QtWidgets.QWidget()
        self.LPR.setObjectName("LPR")
        self.OpenGateButton = QtWidgets.QPushButton(self.LPR)
        self.OpenGateButton.setGeometry(QtCore.QRect(370, 200, 61, 41))
        self.OpenGateButton.setObjectName("OpenGateButton")
        self.CloseGateButton = QtWidgets.QPushButton(self.LPR)
        self.CloseGateButton.setGeometry(QtCore.QRect(460, 200, 61, 41))
        self.CloseGateButton.setObjectName("CloseGateButton")
        self.LPVideo = QtWidgets.QLabel(self.LPR)
        self.LPVideo.setGeometry(QtCore.QRect(20, 30, 320, 240))
        self.LPVideo.setAlignment(QtCore.Qt.AlignCenter)
        self.LPVideo.setObjectName("LPVideo")
        self.LicensePlateInformation_1 = QtWidgets.QLineEdit(self.LPR)
        self.LicensePlateInformation_1.setGeometry(QtCore.QRect(370, 50, 31, 61))
        self.LicensePlateInformation_1.setObjectName("LicensePlateInformation_1")
        self.LicensePlateInformation_2 = QtWidgets.QLineEdit(self.LPR)
        self.LicensePlateInformation_2.setGeometry(QtCore.QRect(400, 50, 31, 61))
        self.LicensePlateInformation_2.setObjectName("LicensePlateInformation_2")
        self.LicensePlateInformation_3 = QtWidgets.QLineEdit(self.LPR)
        self.LicensePlateInformation_3.setGeometry(QtCore.QRect(430, 50, 31, 61))
        self.LicensePlateInformation_3.setObjectName("LicensePlateInformation_3")
        self.LicensePlateInformation_4 = QtWidgets.QLineEdit(self.LPR)
        self.LicensePlateInformation_4.setGeometry(QtCore.QRect(460, 50, 31, 61))
        self.LicensePlateInformation_4.setObjectName("LicensePlateInformation_4")
        self.LicensePlateInformation_5 = QtWidgets.QLineEdit(self.LPR)
        self.LicensePlateInformation_5.setGeometry(QtCore.QRect(490, 50, 31, 61))
        self.LicensePlateInformation_5.setObjectName("LicensePlateInformation_5")
        self.LicensePlateInformation_6 = QtWidgets.QLineEdit(self.LPR)
        self.LicensePlateInformation_6.setGeometry(QtCore.QRect(520, 50, 31, 61))
        self.LicensePlateInformation_6.setObjectName("LicensePlateInformation_6")
        self.LicensePlateInformation_0 = QtWidgets.QLineEdit(self.LPR)
        self.LicensePlateInformation_0.setGeometry(QtCore.QRect(340, 50, 31, 61))
        self.LicensePlateInformation_0.setObjectName("LicensePlateInformation_0")
        self.LicensePlateInformation_7 = QtWidgets.QLineEdit(self.LPR)
        self.LicensePlateInformation_7.setGeometry(QtCore.QRect(340, 120, 211, 41))
        self.LicensePlateInformation_7.setObjectName("LicensePlateInformation_7")
        self.tabWidget.addTab(self.LPR, "")
        self.AutoCar = QtWidgets.QWidget()
        self.AutoCar.setObjectName("AutoCar")
        self.LoadVideoButton = QtWidgets.QPushButton(self.AutoCar)
        self.LoadVideoButton.setGeometry(QtCore.QRect(10, 10, 51, 41))
        self.LoadVideoButton.setObjectName("LoadVideoButton")
        self.StopVideoButton = QtWidgets.QPushButton(self.AutoCar)
        self.StopVideoButton.setGeometry(QtCore.QRect(10, 60, 51, 31))
        self.StopVideoButton.setObjectName("StopVideoButton")
        self.Video = QtWidgets.QLabel(self.AutoCar)
        self.Video.setGeometry(QtCore.QRect(190, 20, 160, 160))
        self.Video.setAlignment(QtCore.Qt.AlignCenter)
        self.Video.setObjectName("Video")
        self.ForwardButton = QtWidgets.QPushButton(self.AutoCar)
        self.ForwardButton.setGeometry(QtCore.QRect(480, 164, 81, 31))
        self.ForwardButton.setObjectName("ForwardButton")
        self.RightButton = QtWidgets.QPushButton(self.AutoCar)
        self.RightButton.setGeometry(QtCore.QRect(480, 210, 81, 31))
        self.RightButton.setObjectName("RightButton")
        self.LeftButton = QtWidgets.QPushButton(self.AutoCar)
        self.LeftButton.setGeometry(QtCore.QRect(10, 210, 81, 31))
        self.LeftButton.setObjectName("LeftButton")
        self.SteerWheel = QtWidgets.QLabel(self.AutoCar)
        self.SteerWheel.setGeometry(QtCore.QRect(226, 206, 101, 71))
        self.SteerWheel.setAlignment(QtCore.Qt.AlignCenter)
        self.SteerWheel.setObjectName("SteerWheel")
        self.tabWidget.addTab(self.AutoCar, "")

        self.retranslateUi(MainWidget)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWidget)

    def retranslateUi(self, MainWidget):
        _translate = QtCore.QCoreApplication.translate
        MainWidget.setWindowTitle(_translate("MainWidget", "Queen Elsa"))
        self.OpenGateButton.setText(_translate("MainWidget", "open"))
        self.CloseGateButton.setText(_translate("MainWidget", "close"))
        self.LPVideo.setText(_translate("MainWidget", "Video"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.LPR), _translate("MainWidget", "LPR"))
        self.LoadVideoButton.setText(_translate("MainWidget", "Open"))
        self.StopVideoButton.setText(_translate("MainWidget", "Close"))
        self.Video.setText(_translate("MainWidget", "Video"))
        self.ForwardButton.setText(_translate("MainWidget", "F"))
        self.RightButton.setText(_translate("MainWidget", "R"))
        self.LeftButton.setText(_translate("MainWidget", "L"))
        self.SteerWheel.setText(_translate("MainWidget", "方向盘"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.AutoCar), _translate("MainWidget", "AutoCar"))
        self.initConnect(MainWidget)

    def initConnect(self, MainWidget):
        self.LoadVideoButton.clicked.connect(MainWidget.imageprocessing) 
        self.StopVideoButton.clicked.connect(MainWidget.videoprocessing) 
        self.LicensePlateInformation_0.setText("蒙")
        self.LicensePlateInformation_0.setAlignment(QtCore.Qt.AlignCenter)
        self.LicensePlateInformation_0.setStyleSheet("color:green")
        self.LicensePlateInformation_1.setText("A")
        self.LicensePlateInformation_1.setAlignment(QtCore.Qt.AlignCenter)
        self.LicensePlateInformation_1.setStyleSheet("color:red")
        self.LicensePlateInformation_2.setText("0")
        self.LicensePlateInformation_2.setAlignment(QtCore.Qt.AlignCenter)
        self.LicensePlateInformation_2.setStyleSheet("color:red")
        self.LicensePlateInformation_3.setText("2")
        self.LicensePlateInformation_3.setAlignment(QtCore.Qt.AlignCenter)
        self.LicensePlateInformation_3.setStyleSheet("color:red")
        self.LicensePlateInformation_4.setText("6")
        self.LicensePlateInformation_4.setAlignment(QtCore.Qt.AlignCenter)
        self.LicensePlateInformation_4.setStyleSheet("color:red")
        self.LicensePlateInformation_5.setText("H")
        self.LicensePlateInformation_5.setAlignment(QtCore.Qt.AlignCenter)
        self.LicensePlateInformation_5.setStyleSheet("color:red")
        self.LicensePlateInformation_6.setText("C")
        self.LicensePlateInformation_6.setAlignment(QtCore.Qt.AlignCenter)
        self.LicensePlateInformation_6.setStyleSheet("color:red")

        self.LicensePlateInformation_7.setText("当前剩余车位：１０")